#!/bin/bash

[ $EUID -eq 0 ] || exec sudo "$0" "$@"
cd "$(dirname "$(readlink -f "$0")")"

case "$1" in
	start) 
		systemctl enable bypass@master-bedroom-roku
		systemctl start bypass@master-bedroom-roku 
		;;
	stop) 
		systemctl disable bypass@master-bedroom-roku
		systemctl stop bypass@master-bedroom-roku 
		;;
	*) 
		echo "start | stop"
		;;
esac


