#!/bin/bash

[ $EUID -eq 0 ] || exec sudo "$0" "$@"
cd "$(dirname "$(readlink -f "$0")")"
squidGuard -C all
squid -k reconfigure
systemctl restart squid
rm -Rf ../bypass/timed/*
rm -Rf ../unblock/timed/*
../apply.sh

